jobs:
  sonarqube:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: PintudosFront
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests with coverage
        run: npm run test -- --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: PINTUDOS-ARSW_PintudosFront
          organization: pintando
          extraProperties: |
            sonar.sources=src
            sonar.sourceEncoding=UTF-8
            sonar.javascript.lcov.reportPaths=coverage/lcov.info
